"""新建模块表

Revision ID: 1ad1b4048064
Revises: be3a6233c1bd
Create Date: 2026-01-26 14:58:31.559704

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad1b4048064'
down_revision: Union[str, Sequence[str], None] = 'be3a6233c1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('testcase', 'session_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testcase', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.drop_table('module')
    # ### end Alembic commands ###
