"""测试用例表关联模块字段

Revision ID: 2b1977bd1d35
Revises: 1ad1b4048064
Create Date: 2026-01-26 17:03:15.194472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import logging


# revision identifiers, used by Alembic.
revision: str = '2b1977bd1d35'
down_revision: Union[str, Sequence[str], None] = '1ad1b4048064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 获取日志记录器
log = logging.getLogger(__name__)


def upgrade() -> None:
    """Upgrade schema."""
    # 获取当前表的列信息
    inspector = sa.inspect(op.get_bind())
    columns = [col['name'] for col in inspector.get_columns('testcase')]
    
    # 只有当module_id列不存在时才添加它
    if 'module_id' not in columns:
        op.add_column('testcase', sa.Column('module_id', sa.Integer(), nullable=True))
        log.info("Column 'module_id' added to 'testcase' table.")
    else:
        log.info("Column 'module_id' already exists in 'testcase' table, skipping addition.")
        
    op.alter_column('testcase', 'session_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testcase', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.drop_column('testcase', 'module_id')
    # ### end Alembic commands ###