"""add bug_id field to TestCase

Revision ID: be3a6233c1bd
Revises: 
Create Date: 2025-12-24 18:26:02.980848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3a6233c1bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testcase', sa.Column('bug_id', sa.Integer(), nullable=True))
    op.alter_column('testcase', 'session_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testcase', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.drop_column('testcase', 'bug_id')
    # ### end Alembic commands ###
